
/**
 * This file is generated by Sencha Cmd and should NOT be edited.  It is 
 * provided to support globbing requires, custom xtypes, and other 
 * metadata-driven class system features 
 */
Ext.Loader.addClassPathMappings({
  " Ext.Msg": "../ext/src/window/MessageBox.js",
  "overrides": "overrides",
  "Ext": "../ext/src",
  "yspz_gen": "app",
  "Ext.rtl.EventObjectImpl": "../ext/src/rtl/EventObject.js",
  "yspz_gen.Application": "app/application.js"
});
Ext.ClassManager.addNameAlternateMappings({
  "overrides.Treepanel": [],
  "Ext.ux.ajax.DataSimlet": [],
  "Ext.ux.grid.TransformGrid": [],
  "yspz_gen.view.component.Books": [],
  "yspz_gen.view.bi.BiBrowser": [],
  "yspz_gen.view.component.Validation": [],
  "Ext.ux.event.Driver": [],
  "Ext.ux.ajax.XmlSimlet": [],
  "overrides.Paging": [],
  "Ext.ux.DataView.DragSelector": [],
  "yspz_gen.view.component.JournalEntry": [],
  "Ext.ux.grid.menu.ListMenu": [],
  "overrides.RowExpander": [],
  "yspz_gen.view.component.Preprocess": [],
  "overrides.Ext": [],
  "yspz_gen.view.verify.yspz_list": [],
  "Ext.ux.form.MultiSelect": [
    "Ext.ux.Multiselect"
  ],
  "yspz_gen.controller.Index": [],
  "yspz_gen.view.bi.InfoPanel": [],
  "yspz_gen.view.yspz_sum.f0002": [],
  "Ext.ux.PreviewPlugin": [],
  "yspz_gen.view.task.gen": [],
  "Ext.ux.ajax.SimXhr": [],
  "yspz_gen.view.yspz.edit": [],
  "Ext.ux.event.RecorderManager": [],
  "Ext.ux.ProgressBarPager": [],
  "Ext.ux.CellDragDrop": [],
  "yspz_gen.view.bi.List": [],
  "yspz_gen.store.CBase": [],
  "Ext.ux.ajax.Simlet": [],
  "Ext.ux.SlidingPager": [],
  "Ext.ux.TabReorderer": [],
  "Ext.ux.grid.filter.NumericFilter": [],
  "yspz_gen.view.Viewport": [],
  "overrides.Gridpanel": [],
  "yspz_gen.view.component.base.CheckBoxGroupSingle": [],
  "Ext.ux.event.Recorder": [],
  "overrides.TabCloseMenu": [],
  "yspz_gen.view.file.badlist": [],
  "yspz_gen.view.file.mgr": [],
  "yspz_gen.store.FStatus": [],
  "Ext.ux.ajax.SimManager": [],
  "yspz_gen.store.Status": [],
  "Ext.ux.grid.filter.BooleanFilter": [],
  "yspz_gen.Application": [],
  "Ext.ux.TabScrollerMenu": [],
  "overrides.RowEditor": [],
  "Ext.ux.IFrame": [],
  "yspz_gen.view.West": [],
  "Ext.ux.form.SearchField": [],
  "Ext.ux.dd.CellFieldDropZone": [],
  "Ext.ux.LiveSearchGridPanel": [],
  "Ext.ux.grid.filter.DateFilter": [],
  "Ext.ux.TreePicker": [],
  "yspz_gen.view.yspz.input": [],
  "yspz_gen.view.North": [],
  "yspz_gen.view.Center": [],
  "Ext.ux.data.PagingMemoryProxy": [
    "Ext.data.PagingMemoryProxy"
  ],
  "yspz_gen.view.component.base.ComboBox": [],
  "Ext.ux.BoxReorderer": [],
  "Ext.ux.grid.filter.Filter": [],
  "Ext.ux.GroupTabRenderer": [],
  "Ext.ux.FieldReplicator": [],
  "Ext.ux.grid.filter.ListFilter": [],
  "yspz_gen.view.task.list": [],
  "yspz_gen.view.component.MyStore": [],
  "Ext.ux.dd.PanelFieldDragZone": [],
  "yspz_gen.view.task.gsum": [],
  "yspz_gen.controller.yspzDict": [],
  "Ext.ux.GMapPanel": [],
  "yspz_gen.view.component.Line": [],
  "yspz_gen.view.yspz.gen": [],
  "Ext.ux.DataView.LabelEditor": [],
  "Ext.ux.GroupTabPanel": [],
  "Ext.ux.grid.filter.StringFilter": [],
  "Ext.ux.statusbar.ValidationStatus": [],
  "yspz_gen.view.component.plugins.PageComboResizer": [],
  "Ext.ux.layout.Center": [],
  "yspz_gen.view.Panel": [],
  "Ext.ux.DataView.Animated": [],
  "overrides.DateField": [],
  "Ext.ux.statusbar.StatusBar": [
    "Ext.ux.StatusBar"
  ],
  "yspz_gen.view.file.goodlist": [],
  "overrides.Table": [],
  "Ext.ux.grid.menu.RangeMenu": [],
  "yspz_gen.view.component.DataType": [],
  "Ext.ux.RowExpander": [],
  "Ext.ux.event.Player": [],
  "yspz_gen.view.South": [],
  "overrides.Connection": [],
  "Ext.ux.ToolbarDroppable": [],
  "Ext.ux.event.Maker": [],
  "yspz_gen.view.component.Set": [],
  "yspz_gen.view.component.QueryForm": [],
  "yspz_gen.view.component.calcValue": [],
  "Ext.ux.DataView.Draggable": [],
  "Ext.ux.TabCloseMenu": [],
  "Ext.ux.DataTip": [],
  "Ext.ux.grid.filter.DateTimeFilter": [],
  "Ext.ux.form.ItemSelector": [
    "Ext.ux.ItemSelector"
  ],
  "Ext.ux.ajax.JsonSimlet": [],
  "Ext.ux.Spotlight": [],
  "Ext.ux.grid.FiltersFeature": [],
  "yspz_gen.view.component.yspzDict": []
});
Ext.ClassManager.addNameAliasMappings({
  "overrides.Treepanel": [],
  "Ext.ux.ajax.DataSimlet": [],
  "Ext.ux.grid.TransformGrid": [],
  "yspz_gen.view.component.Books": [
    "widget.books"
  ],
  "yspz_gen.view.bi.BiBrowser": [
    "widget.bibrowser"
  ],
  "yspz_gen.view.component.Validation": [
    "widget.validation"
  ],
  "Ext.ux.event.Driver": [],
  "Ext.ux.ajax.XmlSimlet": [
    "simlet.xml"
  ],
  "overrides.Paging": [],
  "Ext.ux.DataView.DragSelector": [],
  "yspz_gen.view.component.JournalEntry": [
    "widget.journalentry"
  ],
  "Ext.ux.grid.menu.ListMenu": [],
  "overrides.RowExpander": [],
  "yspz_gen.view.component.Preprocess": [
    "widget.preprocess"
  ],
  "overrides.Ext": [],
  "yspz_gen.view.verify.yspz_list": [
    "widget.verify_yspz_list"
  ],
  "Ext.ux.form.MultiSelect": [
    "widget.multiselect",
    "widget.multiselectfield"
  ],
  "yspz_gen.controller.Index": [],
  "yspz_gen.view.bi.InfoPanel": [
    "widget.infopanel"
  ],
  "yspz_gen.view.yspz_sum.f0002": [
    "widget.yspz_sum_f0002"
  ],
  "Ext.ux.PreviewPlugin": [
    "plugin.preview"
  ],
  "yspz_gen.view.task.gen": [
    "widget.task_gen"
  ],
  "Ext.ux.ajax.SimXhr": [],
  "yspz_gen.view.yspz.edit": [
    "widget.yspz_edit"
  ],
  "Ext.ux.event.RecorderManager": [
    "widget.eventrecordermanager"
  ],
  "Ext.ux.ProgressBarPager": [],
  "Ext.ux.CellDragDrop": [
    "plugin.celldragdrop"
  ],
  "yspz_gen.view.bi.List": [
    "widget.bilist"
  ],
  "yspz_gen.store.CBase": [],
  "Ext.ux.ajax.Simlet": [
    "simlet.basic"
  ],
  "Ext.ux.SlidingPager": [],
  "Ext.ux.TabReorderer": [],
  "Ext.ux.grid.filter.NumericFilter": [
    "gridfilter.numeric"
  ],
  "yspz_gen.view.Viewport": [],
  "overrides.Gridpanel": [],
  "yspz_gen.view.component.base.CheckBoxGroupSingle": [
    "widget.checkboxgroupsingle"
  ],
  "Ext.ux.event.Recorder": [],
  "overrides.TabCloseMenu": [],
  "yspz_gen.view.file.badlist": [
    "widget.badlist"
  ],
  "yspz_gen.view.file.mgr": [
    "widget.file_mgr"
  ],
  "yspz_gen.store.FStatus": [],
  "Ext.ux.ajax.SimManager": [],
  "yspz_gen.store.Status": [],
  "Ext.ux.grid.filter.BooleanFilter": [
    "gridfilter.boolean"
  ],
  "yspz_gen.Application": [],
  "Ext.ux.TabScrollerMenu": [
    "plugin.tabscrollermenu"
  ],
  "overrides.RowEditor": [],
  "Ext.ux.IFrame": [
    "widget.uxiframe"
  ],
  "yspz_gen.view.West": [
    "widget.west"
  ],
  "Ext.ux.form.SearchField": [
    "widget.searchfield"
  ],
  "Ext.ux.dd.CellFieldDropZone": [],
  "Ext.ux.LiveSearchGridPanel": [],
  "Ext.ux.grid.filter.DateFilter": [
    "gridfilter.date"
  ],
  "Ext.ux.TreePicker": [
    "widget.treepicker"
  ],
  "yspz_gen.view.yspz.input": [
    "widget.yspz_input"
  ],
  "yspz_gen.view.North": [
    "widget.north"
  ],
  "yspz_gen.view.Center": [
    "widget.center"
  ],
  "Ext.ux.data.PagingMemoryProxy": [
    "proxy.pagingmemory"
  ],
  "yspz_gen.view.component.base.ComboBox": [],
  "Ext.ux.BoxReorderer": [],
  "Ext.ux.grid.filter.Filter": [],
  "Ext.ux.GroupTabRenderer": [
    "plugin.grouptabrenderer"
  ],
  "Ext.ux.FieldReplicator": [],
  "Ext.ux.grid.filter.ListFilter": [
    "gridfilter.list"
  ],
  "yspz_gen.view.task.list": [
    "widget.task_list"
  ],
  "yspz_gen.view.component.MyStore": [
    "widget.mystore"
  ],
  "Ext.ux.dd.PanelFieldDragZone": [],
  "yspz_gen.view.task.gsum": [
    "widget.task_gsum"
  ],
  "yspz_gen.controller.yspzDict": [],
  "Ext.ux.GMapPanel": [
    "widget.gmappanel"
  ],
  "yspz_gen.view.component.Line": [
    "widget.lines"
  ],
  "yspz_gen.view.yspz.gen": [
    "widget.yspz_gen"
  ],
  "Ext.ux.DataView.LabelEditor": [],
  "Ext.ux.GroupTabPanel": [
    "widget.grouptabpanel"
  ],
  "Ext.ux.grid.filter.StringFilter": [
    "gridfilter.string"
  ],
  "Ext.ux.statusbar.ValidationStatus": [],
  "yspz_gen.view.component.plugins.PageComboResizer": [],
  "Ext.ux.layout.Center": [
    "layout.ux.center"
  ],
  "yspz_gen.view.Panel": [],
  "Ext.ux.DataView.Animated": [],
  "overrides.DateField": [],
  "Ext.ux.statusbar.StatusBar": [
    "widget.statusbar"
  ],
  "yspz_gen.view.file.goodlist": [
    "widget.goodlist"
  ],
  "overrides.Table": [],
  "Ext.ux.grid.menu.RangeMenu": [],
  "yspz_gen.view.component.DataType": [
    "widget.datatype"
  ],
  "Ext.ux.RowExpander": [],
  "Ext.ux.event.Player": [],
  "yspz_gen.view.South": [
    "widget.south"
  ],
  "overrides.Connection": [],
  "Ext.ux.ToolbarDroppable": [],
  "Ext.ux.event.Maker": [],
  "yspz_gen.view.component.Set": [
    "widget.sets"
  ],
  "yspz_gen.view.component.QueryForm": [
    "widget.queryform"
  ],
  "yspz_gen.view.component.calcValue": [
    "widget.calcvalue"
  ],
  "Ext.ux.DataView.Draggable": [],
  "Ext.ux.TabCloseMenu": [
    "plugin.tabclosemenu"
  ],
  "Ext.ux.DataTip": [
    "plugin.datatip"
  ],
  "Ext.ux.grid.filter.DateTimeFilter": [
    "gridfilter.datetime"
  ],
  "Ext.ux.form.ItemSelector": [
    "widget.itemselector",
    "widget.itemselectorfield"
  ],
  "Ext.ux.ajax.JsonSimlet": [
    "simlet.json"
  ],
  "Ext.ux.Spotlight": [],
  "Ext.ux.grid.FiltersFeature": [
    "feature.filters"
  ],
  "yspz_gen.view.component.yspzDict": [
    "widget.yspz_dict"
  ]
});
