
/**
 * This file is generated by Sencha Cmd and should NOT be edited.  It is 
 * provided to support globbing requires, custom xtypes, and other 
 * metadata-driven class system features 
 */
Ext.Loader.addClassPathMappings({
  "demo": "app",
  " Ext.Msg": "../ext/src/window/MessageBox.js",
  "overrides": "overrides",
  "Ext": "../ext/src",
  "demo.Application": "app/application.js",
  "Ext.rtl.EventObjectImpl": "../ext/src/rtl/EventObject.js"
});
Ext.ClassManager.addNameAlternateMappings({
  "Ext.ux.BoxReorderer": [],
  "demo.view.yspz_sum.f0002": [],
  "demo.view.Panel": [],
  "Ext.ux.grid.filter.Filter": [],
  "overrides.Treepanel": [],
  "demo.store.CBase": [],
  "Ext.ux.GroupTabRenderer": [],
  "Ext.ux.grid.TransformGrid": [],
  "Ext.ux.ajax.DataSimlet": [],
  "demo.view.Center": [],
  "Ext.ux.FieldReplicator": [],
  "demo.controller.yspzDict": [],
  "Ext.ux.grid.filter.ListFilter": [],
  "Ext.ux.ajax.XmlSimlet": [],
  "Ext.ux.event.Driver": [],
  "demo.Application": [],
  "demo.view.task.list": [],
  "overrides.Paging": [],
  "Ext.ux.dd.PanelFieldDragZone": [],
  "Ext.ux.DataView.DragSelector": [],
  "demo.view.component.plugins.PageComboResizer": [],
  "demo.store.Status": [],
  "demo.view.component.yspzDict": [],
  "Ext.ux.grid.menu.ListMenu": [],
  "demo.view.Viewport": [],
  "demo.view.South": [],
  "Ext.ux.GMapPanel": [],
  "overrides.RowExpander": [],
  "overrides.Ext": [],
  "Ext.ux.form.MultiSelect": [
    "Ext.ux.Multiselect"
  ],
  "Ext.ux.GroupTabPanel": [],
  "Ext.ux.DataView.LabelEditor": [],
  "Ext.ux.grid.filter.StringFilter": [],
  "Ext.ux.statusbar.ValidationStatus": [],
  "demo.view.West": [],
  "Ext.ux.layout.Center": [],
  "Ext.ux.PreviewPlugin": [],
  "demo.view.component.QueryForm": [],
  "Ext.ux.DataView.Animated": [],
  "Ext.ux.ajax.SimXhr": [],
  "Ext.ux.event.RecorderManager": [],
  "Ext.ux.ProgressBarPager": [],
  "overrides.DateField": [],
  "Ext.ux.CellDragDrop": [],
  "Ext.ux.statusbar.StatusBar": [
    "Ext.ux.StatusBar"
  ],
  "Ext.ux.ajax.Simlet": [],
  "Ext.ux.SlidingPager": [],
  "Ext.ux.TabReorderer": [],
  "Ext.ux.grid.filter.NumericFilter": [],
  "overrides.Gridpanel": [],
  "overrides.Table": [],
  "demo.view.North": [],
  "Ext.ux.grid.menu.RangeMenu": [],
  "Ext.ux.RowExpander": [],
  "Ext.ux.event.Recorder": [],
  "Ext.ux.event.Player": [],
  "overrides.TabCloseMenu": [],
  "demo.view.file.mgr": [],
  "Ext.ux.ajax.SimManager": [],
  "Ext.ux.grid.filter.BooleanFilter": [],
  "overrides.Connection": [],
  "Ext.ux.ToolbarDroppable": [],
  "Ext.ux.event.Maker": [],
  "Ext.ux.TabScrollerMenu": [],
  "Ext.ux.IFrame": [],
  "Ext.ux.DataView.Draggable": [],
  "demo.controller.Index": [],
  "demo.view.file.badlist": [],
  "Ext.ux.TabCloseMenu": [],
  "Ext.ux.form.SearchField": [],
  "Ext.ux.dd.CellFieldDropZone": [],
  "demo.view.file.goodlist": [],
  "demo.view.task.gen": [],
  "Ext.ux.LiveSearchGridPanel": [],
  "Ext.ux.grid.filter.DateFilter": [],
  "Ext.ux.DataTip": [],
  "Ext.ux.grid.filter.DateTimeFilter": [],
  "Ext.ux.TreePicker": [],
  "Ext.ux.form.ItemSelector": [
    "Ext.ux.ItemSelector"
  ],
  "Ext.ux.ajax.JsonSimlet": [],
  "Ext.ux.Spotlight": [],
  "demo.view.component.MyStore": [],
  "Ext.ux.grid.FiltersFeature": [],
  "demo.store.FStatus": [],
  "Ext.ux.data.PagingMemoryProxy": [
    "Ext.data.PagingMemoryProxy"
  ]
});
Ext.ClassManager.addNameAliasMappings({
  "Ext.ux.BoxReorderer": [],
  "demo.view.yspz_sum.f0002": [
    "widget.yspz_sum_f0002"
  ],
  "demo.view.Panel": [],
  "Ext.ux.grid.filter.Filter": [],
  "overrides.Treepanel": [],
  "demo.store.CBase": [],
  "Ext.ux.GroupTabRenderer": [
    "plugin.grouptabrenderer"
  ],
  "Ext.ux.grid.TransformGrid": [],
  "Ext.ux.ajax.DataSimlet": [],
  "demo.view.Center": [
    "widget.center"
  ],
  "Ext.ux.FieldReplicator": [],
  "demo.controller.yspzDict": [],
  "Ext.ux.grid.filter.ListFilter": [
    "gridfilter.list"
  ],
  "Ext.ux.ajax.XmlSimlet": [
    "simlet.xml"
  ],
  "Ext.ux.event.Driver": [],
  "demo.Application": [],
  "demo.view.task.list": [
    "widget.task_list"
  ],
  "overrides.Paging": [],
  "Ext.ux.dd.PanelFieldDragZone": [],
  "Ext.ux.DataView.DragSelector": [],
  "demo.view.component.plugins.PageComboResizer": [],
  "demo.store.Status": [],
  "demo.view.component.yspzDict": [
    "widget.yspz_dict"
  ],
  "Ext.ux.grid.menu.ListMenu": [],
  "demo.view.Viewport": [],
  "demo.view.South": [
    "widget.south"
  ],
  "Ext.ux.GMapPanel": [
    "widget.gmappanel"
  ],
  "overrides.RowExpander": [],
  "overrides.Ext": [],
  "Ext.ux.form.MultiSelect": [
    "widget.multiselect",
    "widget.multiselectfield"
  ],
  "Ext.ux.GroupTabPanel": [
    "widget.grouptabpanel"
  ],
  "Ext.ux.DataView.LabelEditor": [],
  "Ext.ux.grid.filter.StringFilter": [
    "gridfilter.string"
  ],
  "Ext.ux.statusbar.ValidationStatus": [],
  "demo.view.West": [
    "widget.west"
  ],
  "Ext.ux.layout.Center": [
    "layout.ux.center"
  ],
  "Ext.ux.PreviewPlugin": [
    "plugin.preview"
  ],
  "demo.view.component.QueryForm": [
    "widget.queryform"
  ],
  "Ext.ux.DataView.Animated": [],
  "Ext.ux.ajax.SimXhr": [],
  "Ext.ux.event.RecorderManager": [
    "widget.eventrecordermanager"
  ],
  "Ext.ux.ProgressBarPager": [],
  "overrides.DateField": [],
  "Ext.ux.CellDragDrop": [
    "plugin.celldragdrop"
  ],
  "Ext.ux.statusbar.StatusBar": [
    "widget.statusbar"
  ],
  "Ext.ux.ajax.Simlet": [
    "simlet.basic"
  ],
  "Ext.ux.SlidingPager": [],
  "Ext.ux.TabReorderer": [],
  "Ext.ux.grid.filter.NumericFilter": [
    "gridfilter.numeric"
  ],
  "overrides.Gridpanel": [],
  "overrides.Table": [],
  "demo.view.North": [
    "widget.north"
  ],
  "Ext.ux.grid.menu.RangeMenu": [],
  "Ext.ux.RowExpander": [],
  "Ext.ux.event.Recorder": [],
  "Ext.ux.event.Player": [],
  "overrides.TabCloseMenu": [],
  "demo.view.file.mgr": [
    "widget.file_mgr"
  ],
  "Ext.ux.ajax.SimManager": [],
  "Ext.ux.grid.filter.BooleanFilter": [
    "gridfilter.boolean"
  ],
  "overrides.Connection": [],
  "Ext.ux.ToolbarDroppable": [],
  "Ext.ux.event.Maker": [],
  "Ext.ux.TabScrollerMenu": [
    "plugin.tabscrollermenu"
  ],
  "Ext.ux.IFrame": [
    "widget.uxiframe"
  ],
  "Ext.ux.DataView.Draggable": [],
  "demo.controller.Index": [],
  "demo.view.file.badlist": [
    "widget.badlist"
  ],
  "Ext.ux.TabCloseMenu": [
    "plugin.tabclosemenu"
  ],
  "Ext.ux.form.SearchField": [
    "widget.searchfield"
  ],
  "Ext.ux.dd.CellFieldDropZone": [],
  "demo.view.file.goodlist": [
    "widget.goodlist"
  ],
  "demo.view.task.gen": [
    "widget.task_gen"
  ],
  "Ext.ux.LiveSearchGridPanel": [],
  "Ext.ux.grid.filter.DateFilter": [
    "gridfilter.date"
  ],
  "Ext.ux.DataTip": [
    "plugin.datatip"
  ],
  "Ext.ux.grid.filter.DateTimeFilter": [
    "gridfilter.datetime"
  ],
  "Ext.ux.TreePicker": [
    "widget.treepicker"
  ],
  "Ext.ux.form.ItemSelector": [
    "widget.itemselector",
    "widget.itemselectorfield"
  ],
  "Ext.ux.ajax.JsonSimlet": [
    "simlet.json"
  ],
  "Ext.ux.Spotlight": [],
  "demo.view.component.MyStore": [
    "widget.mystore"
  ],
  "Ext.ux.grid.FiltersFeature": [
    "feature.filters"
  ],
  "demo.store.FStatus": [],
  "Ext.ux.data.PagingMemoryProxy": [
    "proxy.pagingmemory"
  ]
});
