
/**
 * This file is generated by Sencha Cmd and should NOT be edited.  It is 
 * provided to support globbing requires, custom xtypes, and other 
 * metadata-driven class system features 
 */
Ext.Loader.addClassPathMappings({
  "Ext.locale.zh_CN.view.AbstractView": "../../../ext/locale/ext-lang-zh_CN.js",
  "Ext.locale.zh_CN.toolbar.Paging": "../../../ext/locale/ext-lang-zh_CN.js",
  "overrides": "../../overrides",
  "Ext.locale.zh_CN.Component": "../../../ext/locale/ext-lang-zh_CN.js",
  "Ext.locale.zh_CN.grid.header.Container": "../../../ext/locale/ext-lang-zh_CN.js",
  "Ext.locale.zh_CN.window.MessageBox": "../../../ext/locale/ext-lang-zh_CN.js",
  "Ext.locale.zh_CN.form.field.Date": "../../../ext/locale/ext-lang-zh_CN.js",
  "Ext.locale.zh_CN.form.field.ComboBox": "../../../ext/locale/ext-lang-zh_CN.js",
  "Ext.locale.zh_CN.form.field.Number": "../../../ext/locale/ext-lang-zh_CN.js",
  "Ext.rtl.EventObjectImpl": "../../../ext/src/rtl/EventObject.js",
  "Ext.locale.zh_CN.view.View": "../../../ext/locale/ext-lang-zh_CN.js",
  "Ext.locale.zh_CN.form.field.Text": "../../../ext/locale/ext-lang-zh_CN.js",
  "Ext.locale.zh_CN.form.field.VTypes": "../../../ext/locale/ext-lang-zh_CN.js",
  "Ext.locale.zh_CN.form.field.Base": "../../../ext/locale/ext-lang-zh_CN.js",
  "Ext.locale.zh_CN.picker.Month": "../../../ext/locale/ext-lang-zh_CN.js",
  " Ext.Msg": "../../../ext/src/window/MessageBox.js",
  "Ext.locale.zh_CN.grid.plugin.DragDrop": "../../../ext/locale/ext-lang-zh_CN.js",
  "yspz_gen": "../../app",
  "Ext": "../../../ext/src",
  "Ext.locale.zh_CN.tab.Tab": "../../../ext/locale/ext-lang-zh_CN.js",
  "Ext.locale.zh_CN.picker.Date": "../../../ext/locale/ext-lang-zh_CN.js",
  "Ext.locale.zh_CN.grid.PropertyColumnModel": "../../../ext/locale/ext-lang-zh_CN.js",
  "Ext.locale.zh_CN.form.field.HtmlEditor": "../../../ext/locale/ext-lang-zh_CN.js",
  "yspz_gen.Application": "../../app/application.js"
});
Ext.ClassManager.addNameAlternateMappings({
  "Ext.locale.zh_CN.toolbar.Paging": [],
  "overrides.Treepanel": [],
  "yspz_gen.view.bi.ProtoPanel": [],
  "Ext.locale.zh_CN.form.field.Date": [],
  "Ext.ux.ajax.DataSimlet": [],
  "Ext.ux.grid.TransformGrid": [],
  "yspz_gen.view.bi.RuleInputPanel": [],
  "yspz_gen.view.zjdz.task.gen": [],
  "yspz_gen.view.bi.BiBrowser": [],
  "yspz_gen.view.component.Books": [],
  "yspz_gen.view.baobiao.task.list": [],
  "yspz_gen.view.bi.FeeInputPanel": [],
  "yspz_gen.view.component.Validation": [],
  "Ext.locale.zh_CN.form.field.VTypes": [],
  "overrides.TreeField": [],
  "Ext.ux.ajax.XmlSimlet": [],
  "Ext.ux.event.Driver": [],
  "yspz_gen.view.bi.DeptAddPanel": [],
  "overrides.Paging": [],
  "Ext.ux.DataView.DragSelector": [],
  "yspz_gen.view.component.JournalEntry": [],
  "Ext.ux.grid.menu.ListMenu": [],
  "Ext.locale.zh_CN.grid.header.Container": [],
  "yspz_gen.view.component.Preprocess": [],
  "overrides.RowExpander": [],
  "Ext.locale.zh_CN.window.MessageBox": [],
  "yspz_gen.view.zjdz.task.list": [],
  "overrides.Ext": [],
  "yspz_gen.view.verify.yspz_list": [],
  "Ext.locale.zh_CN.form.field.Number": [],
  "Ext.ux.form.MultiSelect": [
    "Ext.ux.Multiselect"
  ],
  "yspz_gen.controller.Index": [],
  "Ext.locale.zh_CN.view.View": [],
  "yspz_gen.view.bi.ItemSelectPanel": [],
  "yspz_gen.view.bi.InfoPanel": [],
  "overrides.TabBar": [],
  "yspz_gen.view.task.badlist": [],
  "Ext.locale.zh_CN.picker.Month": [],
  "Ext.ux.PreviewPlugin": [],
  "yspz_gen.view.baobiao.task.add": [],
  "yspz_gen.view.task.gen": [],
  "yspz_gen.view.yspz.edit": [],
  "Ext.ux.ajax.SimXhr": [],
  "Ext.ux.event.RecorderManager": [],
  "yspz_gen.view.yspz_sum.query": [],
  "Ext.ux.ProgressBarPager": [],
  "Ext.locale.zh_CN.form.field.HtmlEditor": [],
  "yspz_gen.view.bi.List": [],
  "Ext.ux.CellDragDrop": [],
  "Ext.locale.zh_CN.view.AbstractView": [],
  "yspz_gen.store.CBase": [],
  "Ext.ux.ajax.Simlet": [],
  "Ext.ux.SlidingPager": [],
  "Ext.locale.zh_CN.Component": [],
  "Ext.ux.TabReorderer": [],
  "yspz_gen.view.baobiao.task.source": [],
  "Ext.ux.grid.filter.NumericFilter": [],
  "yspz_gen.view.bi.BiAddPanel": [],
  "yspz_gen.view.Viewport": [],
  "overrides.Gridpanel": [],
  "yspz_gen.view.component.base.CheckBoxGroupSingle": [],
  "Ext.locale.zh_CN.form.field.Text": [],
  "Ext.ux.event.Recorder": [],
  "yspz_gen.store.CalcValue": [],
  "overrides.TabCloseMenu": [],
  "yspz_gen.view.file.badlist": [],
  "yspz_gen.view.file.mgr": [],
  "yspz_gen.store.FStatus": [],
  "Ext.ux.ajax.SimManager": [],
  "yspz_gen.store.Status": [],
  "Ext.ux.grid.filter.BooleanFilter": [],
  "yspz_gen.Application": [],
  "overrides.RowEditor": [],
  "Ext.ux.TabScrollerMenu": [],
  "Ext.ux.IFrame": [],
  "yspz_gen.view.West": [],
  "Ext.ux.form.SearchField": [],
  "Ext.ux.dd.CellFieldDropZone": [],
  "Ext.ux.LiveSearchGridPanel": [],
  "Ext.ux.grid.filter.DateFilter": [],
  "yspz_gen.view.yspz.input": [],
  "Ext.ux.TreePicker": [],
  "yspz_gen.view.North": [],
  "yspz_gen.view.component.yspz": [],
  "yspz_gen.view.Center": [],
  "Ext.ux.data.PagingMemoryProxy": [
    "Ext.data.PagingMemoryProxy"
  ],
  "yspz_gen.view.component.acct_status": [],
  "yspz_gen.view.component.base.ComboBox": [],
  "Ext.ux.BoxReorderer": [],
  "Ext.ux.grid.filter.Filter": [],
  "Ext.ux.GroupTabRenderer": [],
  "Ext.ux.FieldReplicator": [],
  "yspz_gen.view.zjdz.task.reset": [],
  "Ext.locale.zh_CN.form.field.Base": [],
  "Ext.ux.grid.filter.ListFilter": [],
  "yspz_gen.view.task.list": [],
  "Ext.locale.zh_CN.grid.plugin.DragDrop": [],
  "yspz_gen.view.component.MyStore": [],
  "yspz_gen.view.baobiao.task.edit": [],
  "yspz_gen.view.zjdz.task.dz": [],
  "Ext.ux.dd.PanelFieldDragZone": [],
  "yspz_gen.view.task.gsum": [],
  "yspz_gen.controller.yspzDict": [],
  "yspz_gen.view.bi.ProtoAddPanel": [],
  "yspz_gen.view.baobiao.task.mcheck": [],
  "yspz_gen.view.component.base.PagingInfo": [],
  "yspz_gen.view.component.bfj_acct": [],
  "yspz_gen.view.component.Line": [],
  "Ext.ux.GMapPanel": [],
  "yspz_gen.view.component.pay_cycle": [],
  "Ext.ux.GroupTabPanel": [],
  "Ext.ux.DataView.LabelEditor": [],
  "yspz_gen.view.component.rule": [],
  "Ext.ux.grid.filter.StringFilter": [],
  "yspz_gen.view.yspz.list": [],
  "Ext.ux.statusbar.ValidationStatus": [],
  "yspz_gen.view.component.plugins.PageComboResizer": [],
  "Ext.ux.layout.Center": [],
  "yspz_gen.view.Panel": [],
  "Ext.ux.DataView.Animated": [],
  "yspz_gen.view.bi.BiPanel": [],
  "overrides.DateField": [],
  "Ext.ux.statusbar.StatusBar": [
    "Ext.ux.StatusBar"
  ],
  "yspz_gen.view.component.bank": [],
  "yspz_gen.view.file.goodlist": [],
  "overrides.Table": [],
  "Ext.ux.grid.menu.RangeMenu": [],
  "yspz_gen.view.component.DataType": [],
  "Ext.ux.RowExpander": [],
  "Ext.ux.event.Player": [],
  "yspz_gen.view.South": [],
  "Ext.locale.zh_CN.tab.Tab": [],
  "yspz_gen.view.zjdz.task.adjust": [],
  "overrides.Connection": [],
  "Ext.locale.zh_CN.grid.PropertyColumnModel": [],
  "Ext.ux.ToolbarDroppable": [],
  "Ext.ux.event.Maker": [],
  "yspz_gen.view.component.Set": [],
  "yspz_gen.view.component.QueryForm": [],
  "yspz_gen.view.component.calcValue": [],
  "Ext.ux.DataView.Draggable": [],
  "Ext.locale.zh_CN.form.field.ComboBox": [],
  "Ext.ux.TabCloseMenu": [],
  "Ext.ux.DataTip": [],
  "Ext.ux.grid.filter.DateTimeFilter": [],
  "Ext.ux.form.ItemSelector": [
    "Ext.ux.ItemSelector"
  ],
  "Ext.ux.ajax.JsonSimlet": [],
  "Ext.ux.Spotlight": [],
  "Ext.ux.grid.FiltersFeature": [],
  "Ext.locale.zh_CN.picker.Date": [],
  "yspz_gen.view.component.yspzDict": [],
  "yspz_gen.view.yspz.list-bak": []
});
Ext.ClassManager.addNameAliasMappings({
  "Ext.locale.zh_CN.toolbar.Paging": [],
  "overrides.Treepanel": [],
  "yspz_gen.view.bi.ProtoPanel": [
    "widget.protopanel"
  ],
  "Ext.locale.zh_CN.form.field.Date": [],
  "Ext.ux.ajax.DataSimlet": [],
  "Ext.ux.grid.TransformGrid": [],
  "yspz_gen.view.bi.RuleInputPanel": [
    "widget.bi_ruleinputpanel"
  ],
  "yspz_gen.view.zjdz.task.gen": [
    "widget.zjdz_task_gen"
  ],
  "yspz_gen.view.bi.BiBrowser": [
    "widget.bibrowser"
  ],
  "yspz_gen.view.component.Books": [
    "widget.books"
  ],
  "yspz_gen.view.baobiao.task.list": [
    "widget.baobiao_task_list"
  ],
  "yspz_gen.view.bi.FeeInputPanel": [
    "widget.bi_feeinputpanel"
  ],
  "yspz_gen.view.component.Validation": [
    "widget.validation"
  ],
  "Ext.locale.zh_CN.form.field.VTypes": [],
  "overrides.TreeField": [],
  "Ext.ux.ajax.XmlSimlet": [
    "simlet.xml"
  ],
  "Ext.ux.event.Driver": [],
  "yspz_gen.view.bi.DeptAddPanel": [
    "widget.dept_add"
  ],
  "overrides.Paging": [],
  "Ext.ux.DataView.DragSelector": [],
  "yspz_gen.view.component.JournalEntry": [
    "widget.journalentry"
  ],
  "Ext.ux.grid.menu.ListMenu": [],
  "Ext.locale.zh_CN.grid.header.Container": [],
  "yspz_gen.view.component.Preprocess": [
    "widget.preprocess"
  ],
  "overrides.RowExpander": [],
  "Ext.locale.zh_CN.window.MessageBox": [],
  "yspz_gen.view.zjdz.task.list": [
    "widget.zjdz_task_list"
  ],
  "overrides.Ext": [],
  "yspz_gen.view.verify.yspz_list": [
    "widget.verify_yspz_list"
  ],
  "Ext.locale.zh_CN.form.field.Number": [],
  "Ext.ux.form.MultiSelect": [
    "widget.multiselect",
    "widget.multiselectfield"
  ],
  "yspz_gen.controller.Index": [],
  "Ext.locale.zh_CN.view.View": [],
  "yspz_gen.view.bi.ItemSelectPanel": [
    "widget.bi_itemselectpanel"
  ],
  "yspz_gen.view.bi.InfoPanel": [
    "widget.infopanel"
  ],
  "overrides.TabBar": [],
  "yspz_gen.view.task.badlist": [
    "widget.bad_list"
  ],
  "Ext.locale.zh_CN.picker.Month": [],
  "Ext.ux.PreviewPlugin": [
    "plugin.preview"
  ],
  "yspz_gen.view.baobiao.task.add": [
    "widget.baobiao_task_add"
  ],
  "yspz_gen.view.task.gen": [
    "widget.task_gen"
  ],
  "yspz_gen.view.yspz.edit": [
    "widget.yspz_edit"
  ],
  "Ext.ux.ajax.SimXhr": [],
  "Ext.ux.event.RecorderManager": [
    "widget.eventrecordermanager"
  ],
  "yspz_gen.view.yspz_sum.query": [
    "widget.sum_query"
  ],
  "Ext.ux.ProgressBarPager": [],
  "Ext.locale.zh_CN.form.field.HtmlEditor": [],
  "yspz_gen.view.bi.List": [
    "widget.bi_list"
  ],
  "Ext.ux.CellDragDrop": [
    "plugin.celldragdrop"
  ],
  "Ext.locale.zh_CN.view.AbstractView": [],
  "yspz_gen.store.CBase": [],
  "Ext.ux.ajax.Simlet": [
    "simlet.basic"
  ],
  "Ext.ux.SlidingPager": [],
  "Ext.locale.zh_CN.Component": [],
  "Ext.ux.TabReorderer": [],
  "yspz_gen.view.baobiao.task.source": [
    "widget.baobiao_task_source"
  ],
  "Ext.ux.grid.filter.NumericFilter": [
    "gridfilter.numeric"
  ],
  "yspz_gen.view.bi.BiAddPanel": [
    "widget.bi_add"
  ],
  "yspz_gen.view.Viewport": [],
  "overrides.Gridpanel": [],
  "yspz_gen.view.component.base.CheckBoxGroupSingle": [
    "widget.checkboxgroupsingle"
  ],
  "Ext.locale.zh_CN.form.field.Text": [],
  "Ext.ux.event.Recorder": [],
  "yspz_gen.store.CalcValue": [],
  "overrides.TabCloseMenu": [],
  "yspz_gen.view.file.badlist": [
    "widget.badlist"
  ],
  "yspz_gen.view.file.mgr": [
    "widget.file_mgr"
  ],
  "yspz_gen.store.FStatus": [],
  "Ext.ux.ajax.SimManager": [],
  "yspz_gen.store.Status": [],
  "Ext.ux.grid.filter.BooleanFilter": [
    "gridfilter.boolean"
  ],
  "yspz_gen.Application": [],
  "overrides.RowEditor": [],
  "Ext.ux.TabScrollerMenu": [
    "plugin.tabscrollermenu"
  ],
  "Ext.ux.IFrame": [
    "widget.uxiframe"
  ],
  "yspz_gen.view.West": [
    "widget.west"
  ],
  "Ext.ux.form.SearchField": [
    "widget.searchfield"
  ],
  "Ext.ux.dd.CellFieldDropZone": [],
  "Ext.ux.LiveSearchGridPanel": [],
  "Ext.ux.grid.filter.DateFilter": [
    "gridfilter.date"
  ],
  "yspz_gen.view.yspz.input": [
    "widget.yspz_input"
  ],
  "Ext.ux.TreePicker": [
    "widget.treepicker"
  ],
  "yspz_gen.view.North": [
    "widget.north"
  ],
  "yspz_gen.view.component.yspz": [
    "widget.yspz"
  ],
  "yspz_gen.view.Center": [
    "widget.center"
  ],
  "Ext.ux.data.PagingMemoryProxy": [
    "proxy.pagingmemory"
  ],
  "yspz_gen.view.component.acct_status": [
    "widget.acct_status"
  ],
  "yspz_gen.view.component.base.ComboBox": [],
  "Ext.ux.BoxReorderer": [],
  "Ext.ux.grid.filter.Filter": [],
  "Ext.ux.GroupTabRenderer": [
    "plugin.grouptabrenderer"
  ],
  "Ext.ux.FieldReplicator": [],
  "yspz_gen.view.zjdz.task.reset": [
    "widget.zjdz_task_reset"
  ],
  "Ext.locale.zh_CN.form.field.Base": [],
  "Ext.ux.grid.filter.ListFilter": [
    "gridfilter.list"
  ],
  "yspz_gen.view.task.list": [
    "widget.task_list"
  ],
  "Ext.locale.zh_CN.grid.plugin.DragDrop": [],
  "yspz_gen.view.component.MyStore": [
    "widget.mystore"
  ],
  "yspz_gen.view.baobiao.task.edit": [
    "widget.baobiao_task_edit"
  ],
  "yspz_gen.view.zjdz.task.dz": [
    "widget.zjdz_task_dz"
  ],
  "Ext.ux.dd.PanelFieldDragZone": [],
  "yspz_gen.view.task.gsum": [
    "widget.task_gsum"
  ],
  "yspz_gen.controller.yspzDict": [],
  "yspz_gen.view.bi.ProtoAddPanel": [
    "widget.proto_add"
  ],
  "yspz_gen.view.baobiao.task.mcheck": [
    "widget.baobiao_task_mcheck"
  ],
  "yspz_gen.view.component.base.PagingInfo": [
    "widget.paginginfo"
  ],
  "yspz_gen.view.component.bfj_acct": [
    "widget.bfj_acct"
  ],
  "yspz_gen.view.component.Line": [
    "widget.lines"
  ],
  "Ext.ux.GMapPanel": [
    "widget.gmappanel"
  ],
  "yspz_gen.view.component.pay_cycle": [
    "widget.pay_cycle"
  ],
  "Ext.ux.GroupTabPanel": [
    "widget.grouptabpanel"
  ],
  "Ext.ux.DataView.LabelEditor": [],
  "yspz_gen.view.component.rule": [
    "widget.rule"
  ],
  "Ext.ux.grid.filter.StringFilter": [
    "gridfilter.string"
  ],
  "yspz_gen.view.yspz.list": [
    "widget.yspz_list"
  ],
  "Ext.ux.statusbar.ValidationStatus": [],
  "yspz_gen.view.component.plugins.PageComboResizer": [],
  "Ext.ux.layout.Center": [
    "layout.ux.center"
  ],
  "yspz_gen.view.Panel": [],
  "Ext.ux.DataView.Animated": [],
  "yspz_gen.view.bi.BiPanel": [
    "widget.bipanel"
  ],
  "overrides.DateField": [],
  "Ext.ux.statusbar.StatusBar": [
    "widget.statusbar"
  ],
  "yspz_gen.view.component.bank": [
    "widget.bank"
  ],
  "yspz_gen.view.file.goodlist": [
    "widget.goodlist"
  ],
  "overrides.Table": [],
  "Ext.ux.grid.menu.RangeMenu": [],
  "yspz_gen.view.component.DataType": [
    "widget.datatype"
  ],
  "Ext.ux.RowExpander": [],
  "Ext.ux.event.Player": [],
  "yspz_gen.view.South": [
    "widget.south"
  ],
  "Ext.locale.zh_CN.tab.Tab": [],
  "yspz_gen.view.zjdz.task.adjust": [
    "widget.zjdz_task_adjust"
  ],
  "overrides.Connection": [],
  "Ext.locale.zh_CN.grid.PropertyColumnModel": [],
  "Ext.ux.ToolbarDroppable": [],
  "Ext.ux.event.Maker": [],
  "yspz_gen.view.component.Set": [
    "widget.sets"
  ],
  "yspz_gen.view.component.QueryForm": [
    "widget.queryform"
  ],
  "yspz_gen.view.component.calcValue": [
    "widget.calcvalue"
  ],
  "Ext.ux.DataView.Draggable": [],
  "Ext.locale.zh_CN.form.field.ComboBox": [],
  "Ext.ux.TabCloseMenu": [
    "plugin.tabclosemenu"
  ],
  "Ext.ux.DataTip": [
    "plugin.datatip"
  ],
  "Ext.ux.grid.filter.DateTimeFilter": [
    "gridfilter.datetime"
  ],
  "Ext.ux.form.ItemSelector": [
    "widget.itemselector",
    "widget.itemselectorfield"
  ],
  "Ext.ux.ajax.JsonSimlet": [
    "simlet.json"
  ],
  "Ext.ux.Spotlight": [],
  "Ext.ux.grid.FiltersFeature": [
    "feature.filters"
  ],
  "Ext.locale.zh_CN.picker.Date": [],
  "yspz_gen.view.component.yspzDict": [
    "widget.yspz_dict"
  ],
  "yspz_gen.view.yspz.list-bak": [
    "widget.yspz_list_bak"
  ]
});
