
/**
 * This file is generated by Sencha Cmd and should NOT be edited.  It is 
 * provided to support globbing requires, custom xtypes, and other 
 * metadata-driven class system features 
 */
Ext.Loader.addClassPathMappings({
  "demo": "../../app",
  "Ext.locale.zh_CN.view.AbstractView": "../../../ext/locale/ext-lang-zh_CN.js",
  "Ext.locale.zh_CN.toolbar.Paging": "../../../ext/locale/ext-lang-zh_CN.js",
  "overrides": "../../overrides",
  "Ext.locale.zh_CN.Component": "../../../ext/locale/ext-lang-zh_CN.js",
  "Ext.locale.zh_CN.grid.header.Container": "../../../ext/locale/ext-lang-zh_CN.js",
  "Ext.locale.zh_CN.window.MessageBox": "../../../ext/locale/ext-lang-zh_CN.js",
  "Ext.locale.zh_CN.form.field.Date": "../../../ext/locale/ext-lang-zh_CN.js",
  "Ext.locale.zh_CN.form.field.ComboBox": "../../../ext/locale/ext-lang-zh_CN.js",
  "Ext.locale.zh_CN.form.field.Number": "../../../ext/locale/ext-lang-zh_CN.js",
  "Ext.rtl.EventObjectImpl": "../../../ext/src/rtl/EventObject.js",
  "Ext.locale.zh_CN.view.View": "../../../ext/locale/ext-lang-zh_CN.js",
  "Ext.locale.zh_CN.form.field.Text": "../../../ext/locale/ext-lang-zh_CN.js",
  "Ext.locale.zh_CN.form.field.VTypes": "../../../ext/locale/ext-lang-zh_CN.js",
  "Ext.locale.zh_CN.form.field.Base": "../../../ext/locale/ext-lang-zh_CN.js",
  "Ext.locale.zh_CN.picker.Month": "../../../ext/locale/ext-lang-zh_CN.js",
  " Ext.Msg": "../../../ext/src/window/MessageBox.js",
  "Ext.locale.zh_CN.grid.plugin.DragDrop": "../../../ext/locale/ext-lang-zh_CN.js",
  "Ext": "../../../ext/src",
  "Ext.locale.zh_CN.tab.Tab": "../../../ext/locale/ext-lang-zh_CN.js",
  "demo.Application": "../../app/application.js",
  "Ext.locale.zh_CN.picker.Date": "../../../ext/locale/ext-lang-zh_CN.js",
  "Ext.locale.zh_CN.grid.PropertyColumnModel": "../../../ext/locale/ext-lang-zh_CN.js",
  "Ext.locale.zh_CN.form.field.HtmlEditor": "../../../ext/locale/ext-lang-zh_CN.js"
});
Ext.ClassManager.addNameAlternateMappings({
  "Ext.locale.zh_CN.toolbar.Paging": [],
  "demo.view.yspz_sum.f0002": [],
  "overrides.Treepanel": [],
  "Ext.locale.zh_CN.form.field.Date": [],
  "Ext.ux.ajax.DataSimlet": [],
  "Ext.ux.grid.TransformGrid": [],
  "demo.view.Center": [],
  "demo.controller.yspzDict": [],
  "Ext.locale.zh_CN.form.field.VTypes": [],
  "Ext.ux.ajax.XmlSimlet": [],
  "Ext.ux.event.Driver": [],
  "overrides.Paging": [],
  "Ext.ux.DataView.DragSelector": [],
  "demo.view.component.plugins.PageComboResizer": [],
  "Ext.ux.grid.menu.ListMenu": [],
  "demo.view.component.yspzDict": [],
  "demo.view.Viewport": [],
  "Ext.locale.zh_CN.grid.header.Container": [],
  "Ext.locale.zh_CN.window.MessageBox": [],
  "overrides.RowExpander": [],
  "overrides.Ext": [],
  "Ext.locale.zh_CN.form.field.Number": [],
  "Ext.ux.form.MultiSelect": [
    "Ext.ux.Multiselect"
  ],
  "Ext.locale.zh_CN.view.View": [],
  "demo.view.West": [],
  "Ext.locale.zh_CN.picker.Month": [],
  "Ext.ux.PreviewPlugin": [],
  "Ext.ux.ajax.SimXhr": [],
  "Ext.ux.event.RecorderManager": [],
  "Ext.ux.ProgressBarPager": [],
  "Ext.locale.zh_CN.form.field.HtmlEditor": [],
  "Ext.ux.CellDragDrop": [],
  "Ext.locale.zh_CN.view.AbstractView": [],
  "Ext.ux.ajax.Simlet": [],
  "Ext.ux.SlidingPager": [],
  "Ext.locale.zh_CN.Component": [],
  "Ext.ux.TabReorderer": [],
  "Ext.ux.grid.filter.NumericFilter": [],
  "overrides.Gridpanel": [],
  "Ext.locale.zh_CN.form.field.Text": [],
  "Ext.ux.event.Recorder": [],
  "overrides.TabCloseMenu": [],
  "demo.view.file.mgr": [],
  "Ext.ux.ajax.SimManager": [],
  "Ext.ux.grid.filter.BooleanFilter": [],
  "Ext.ux.TabScrollerMenu": [],
  "Ext.ux.IFrame": [],
  "demo.view.file.badlist": [],
  "Ext.ux.form.SearchField": [],
  "Ext.ux.dd.CellFieldDropZone": [],
  "demo.view.file.goodlist": [],
  "Ext.ux.LiveSearchGridPanel": [],
  "Ext.ux.grid.filter.DateFilter": [],
  "Ext.ux.TreePicker": [],
  "demo.view.component.MyStore": [],
  "Ext.ux.data.PagingMemoryProxy": [
    "Ext.data.PagingMemoryProxy"
  ],
  "demo.store.FStatus": [],
  "Ext.ux.BoxReorderer": [],
  "demo.view.Panel": [],
  "Ext.ux.grid.filter.Filter": [],
  "Ext.ux.GroupTabRenderer": [],
  "demo.store.CBase": [],
  "Ext.ux.FieldReplicator": [],
  "Ext.locale.zh_CN.form.field.Base": [],
  "Ext.ux.grid.filter.ListFilter": [],
  "Ext.locale.zh_CN.grid.plugin.DragDrop": [],
  "demo.Application": [],
  "demo.view.task.list": [],
  "Ext.ux.dd.PanelFieldDragZone": [],
  "demo.store.Status": [],
  "Ext.ux.GMapPanel": [],
  "demo.view.South": [],
  "Ext.ux.GroupTabPanel": [],
  "Ext.ux.DataView.LabelEditor": [],
  "Ext.ux.grid.filter.StringFilter": [],
  "Ext.ux.statusbar.ValidationStatus": [],
  "Ext.ux.layout.Center": [],
  "demo.view.component.QueryForm": [],
  "Ext.ux.DataView.Animated": [],
  "overrides.DateField": [],
  "Ext.ux.statusbar.StatusBar": [
    "Ext.ux.StatusBar"
  ],
  "overrides.Table": [],
  "Ext.ux.grid.menu.RangeMenu": [],
  "demo.view.North": [],
  "Ext.ux.RowExpander": [],
  "Ext.ux.event.Player": [],
  "Ext.locale.zh_CN.tab.Tab": [],
  "overrides.Connection": [],
  "Ext.locale.zh_CN.grid.PropertyColumnModel": [],
  "Ext.ux.ToolbarDroppable": [],
  "Ext.ux.event.Maker": [],
  "Ext.ux.DataView.Draggable": [],
  "demo.controller.Index": [],
  "Ext.locale.zh_CN.form.field.ComboBox": [],
  "Ext.ux.TabCloseMenu": [],
  "demo.view.task.gen": [],
  "Ext.ux.DataTip": [],
  "Ext.ux.grid.filter.DateTimeFilter": [],
  "Ext.ux.form.ItemSelector": [
    "Ext.ux.ItemSelector"
  ],
  "Ext.ux.ajax.JsonSimlet": [],
  "Ext.ux.Spotlight": [],
  "Ext.ux.grid.FiltersFeature": [],
  "Ext.locale.zh_CN.picker.Date": []
});
Ext.ClassManager.addNameAliasMappings({
  "Ext.locale.zh_CN.toolbar.Paging": [],
  "demo.view.yspz_sum.f0002": [
    "widget.yspz_sum_f0002"
  ],
  "overrides.Treepanel": [],
  "Ext.locale.zh_CN.form.field.Date": [],
  "Ext.ux.ajax.DataSimlet": [],
  "Ext.ux.grid.TransformGrid": [],
  "demo.view.Center": [
    "widget.center"
  ],
  "demo.controller.yspzDict": [],
  "Ext.locale.zh_CN.form.field.VTypes": [],
  "Ext.ux.ajax.XmlSimlet": [
    "simlet.xml"
  ],
  "Ext.ux.event.Driver": [],
  "overrides.Paging": [],
  "Ext.ux.DataView.DragSelector": [],
  "demo.view.component.plugins.PageComboResizer": [],
  "Ext.ux.grid.menu.ListMenu": [],
  "demo.view.component.yspzDict": [
    "widget.yspz_dict"
  ],
  "demo.view.Viewport": [],
  "Ext.locale.zh_CN.grid.header.Container": [],
  "Ext.locale.zh_CN.window.MessageBox": [],
  "overrides.RowExpander": [],
  "overrides.Ext": [],
  "Ext.locale.zh_CN.form.field.Number": [],
  "Ext.ux.form.MultiSelect": [
    "widget.multiselect",
    "widget.multiselectfield"
  ],
  "Ext.locale.zh_CN.view.View": [],
  "demo.view.West": [
    "widget.west"
  ],
  "Ext.locale.zh_CN.picker.Month": [],
  "Ext.ux.PreviewPlugin": [
    "plugin.preview"
  ],
  "Ext.ux.ajax.SimXhr": [],
  "Ext.ux.event.RecorderManager": [
    "widget.eventrecordermanager"
  ],
  "Ext.ux.ProgressBarPager": [],
  "Ext.locale.zh_CN.form.field.HtmlEditor": [],
  "Ext.ux.CellDragDrop": [
    "plugin.celldragdrop"
  ],
  "Ext.locale.zh_CN.view.AbstractView": [],
  "Ext.ux.ajax.Simlet": [
    "simlet.basic"
  ],
  "Ext.ux.SlidingPager": [],
  "Ext.locale.zh_CN.Component": [],
  "Ext.ux.TabReorderer": [],
  "Ext.ux.grid.filter.NumericFilter": [
    "gridfilter.numeric"
  ],
  "overrides.Gridpanel": [],
  "Ext.locale.zh_CN.form.field.Text": [],
  "Ext.ux.event.Recorder": [],
  "overrides.TabCloseMenu": [],
  "demo.view.file.mgr": [
    "widget.file_mgr"
  ],
  "Ext.ux.ajax.SimManager": [],
  "Ext.ux.grid.filter.BooleanFilter": [
    "gridfilter.boolean"
  ],
  "Ext.ux.TabScrollerMenu": [
    "plugin.tabscrollermenu"
  ],
  "Ext.ux.IFrame": [
    "widget.uxiframe"
  ],
  "demo.view.file.badlist": [
    "widget.badlist"
  ],
  "Ext.ux.form.SearchField": [
    "widget.searchfield"
  ],
  "Ext.ux.dd.CellFieldDropZone": [],
  "demo.view.file.goodlist": [
    "widget.goodlist"
  ],
  "Ext.ux.LiveSearchGridPanel": [],
  "Ext.ux.grid.filter.DateFilter": [
    "gridfilter.date"
  ],
  "Ext.ux.TreePicker": [
    "widget.treepicker"
  ],
  "demo.view.component.MyStore": [
    "widget.mystore"
  ],
  "Ext.ux.data.PagingMemoryProxy": [
    "proxy.pagingmemory"
  ],
  "demo.store.FStatus": [],
  "Ext.ux.BoxReorderer": [],
  "demo.view.Panel": [],
  "Ext.ux.grid.filter.Filter": [],
  "Ext.ux.GroupTabRenderer": [
    "plugin.grouptabrenderer"
  ],
  "demo.store.CBase": [],
  "Ext.ux.FieldReplicator": [],
  "Ext.locale.zh_CN.form.field.Base": [],
  "Ext.ux.grid.filter.ListFilter": [
    "gridfilter.list"
  ],
  "Ext.locale.zh_CN.grid.plugin.DragDrop": [],
  "demo.Application": [],
  "demo.view.task.list": [
    "widget.task_list"
  ],
  "Ext.ux.dd.PanelFieldDragZone": [],
  "demo.store.Status": [],
  "Ext.ux.GMapPanel": [
    "widget.gmappanel"
  ],
  "demo.view.South": [
    "widget.south"
  ],
  "Ext.ux.GroupTabPanel": [
    "widget.grouptabpanel"
  ],
  "Ext.ux.DataView.LabelEditor": [],
  "Ext.ux.grid.filter.StringFilter": [
    "gridfilter.string"
  ],
  "Ext.ux.statusbar.ValidationStatus": [],
  "Ext.ux.layout.Center": [
    "layout.ux.center"
  ],
  "demo.view.component.QueryForm": [
    "widget.queryform"
  ],
  "Ext.ux.DataView.Animated": [],
  "overrides.DateField": [],
  "Ext.ux.statusbar.StatusBar": [
    "widget.statusbar"
  ],
  "overrides.Table": [],
  "Ext.ux.grid.menu.RangeMenu": [],
  "demo.view.North": [
    "widget.north"
  ],
  "Ext.ux.RowExpander": [],
  "Ext.ux.event.Player": [],
  "Ext.locale.zh_CN.tab.Tab": [],
  "overrides.Connection": [],
  "Ext.locale.zh_CN.grid.PropertyColumnModel": [],
  "Ext.ux.ToolbarDroppable": [],
  "Ext.ux.event.Maker": [],
  "Ext.ux.DataView.Draggable": [],
  "demo.controller.Index": [],
  "Ext.locale.zh_CN.form.field.ComboBox": [],
  "Ext.ux.TabCloseMenu": [
    "plugin.tabclosemenu"
  ],
  "demo.view.task.gen": [
    "widget.task_gen"
  ],
  "Ext.ux.DataTip": [
    "plugin.datatip"
  ],
  "Ext.ux.grid.filter.DateTimeFilter": [
    "gridfilter.datetime"
  ],
  "Ext.ux.form.ItemSelector": [
    "widget.itemselector",
    "widget.itemselectorfield"
  ],
  "Ext.ux.ajax.JsonSimlet": [
    "simlet.json"
  ],
  "Ext.ux.Spotlight": [],
  "Ext.ux.grid.FiltersFeature": [
    "feature.filters"
  ],
  "Ext.locale.zh_CN.picker.Date": []
});
